# Generated by Django 6.0.1 on 2026-03-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_readingprogress_reading_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('science', 'Science & Technology'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('motivational', 'Motivational'), ('fiction', 'Fiction'), ('biography', 'Biography'), ('history', 'History'), ('mystery & thriller', 'Mystery & Thriller')], max_length=50),
        ),
    ]
