# Generated by Django 6.0.2 on 2026-07-27 13:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_readingprogress_reading_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('science', 'Science & Technology'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('motivational', 'Motivational'), ('fiction', 'Fiction'), ('biography', 'Biography'), ('history', 'History'), ('mystery & thriller', 'Mystery & Thriller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='covers/'),
        ),
    ]
